# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: restaurant.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'restaurant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10restaurant.proto\"\x1f\n\x11RestaurantRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"C\n\x12RestaurantResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x02\x32M\n\x11RestaurantService\x12\x38\n\rGetRestaurant\x12\x12.RestaurantRequest\x1a\x13.RestaurantResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'restaurant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESTAURANTREQUEST']._serialized_start=20
  _globals['_RESTAURANTREQUEST']._serialized_end=51
  _globals['_RESTAURANTRESPONSE']._serialized_start=53
  _globals['_RESTAURANTRESPONSE']._serialized_end=120
  _globals['_RESTAURANTSERVICE']._serialized_start=122
  _globals['_RESTAURANTSERVICE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
